steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG}', 'gs://gs://wissen-tesst/wissen-test/']


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG}']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG}'
    - '--platform'
    - 'managed'
    - '--region'
    - '${_REGION}'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG}'

substitutions:
  _PROJECT_ID: 'useful-builder-427720-a1'
  _REGION: 'asia-south1'  
  _SERVICE_NAME: 'wissen-demo'
  _IMAGE_NAME: 'wissen-test'
  _TAG: 'latest'
