steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_ARTIFACT_REGISTRY/$_IMAGE_NAME:$_TAG', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_ARTIFACT_REGISTRY/$_IMAGE_NAME:$_TAG']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_ARTIFACT_REGISTRY/$_IMAGE_NAME:$_TAG'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - '$_ARTIFACT_REGISTRY/$_IMAGE_NAME:$_TAG'

substitutions:
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev/useful-builder-427720-a1/gcf-artifacts'       # Change to your Artifact Registry path
  _IMAGE_NAME: 'rakesh-demo'
  _TAG: 'latest'
  _SERVICE_NAME: 'my-cloud-run-service'              # Cloud Run service name
  _REGION: 'us-central1'  # Cloud Run region

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
